config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles do
    resources :comments
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord 
    has_many :comments
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 100, maximum: 900}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord

    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
  validates :username, presence: true, 
      uniqueness: { case_sensitive: false }, length: { minimum: 6, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,  uniqueness: { case_sensitive: false }, 
      length: { maximum: 105 }, 
      format: { with: VALID_EMAIL_REGEX }
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end
   
    def require_user
        if !logged_in?
            flash[:alert] = "You must log in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    
    def show
      
        end 
       
        def index
            @articles = Article.paginate(page: params[:page], per_page: 2)
        end 

        def new
            @article = Article.new
        end
        def edit
        end
        def create
            @article = Article.new(article_params)
            @article.user = current_user
           if @article.save
             flash[:notice] = "Article was created succefully."
            redirect_to @article
           else 
            render 'new'
        end
    end 

    def update
        if @article.update(article_params)
          flash[:notice] = "Article was updated successfully."
          redirect_to @article
        else
          render 'edit'
        end
      end

      def destroy
        @article.destroy
        redirect_to articles_path
      end
     
      private

      def set_article
      @article = Article.find(params[:id])
      end 

      def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
      end
      
      def require_same_user
        if current_user != @article.user && !current_user.admin?
          flash[:alert] = "You can only edit or delete your own article"
          redirect_to @article
        end
      end

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 
    before_action :require_admin, except: [:index, :show]

    def new
     @category = Category.new
    end
     
    def create
     @category = Category.new(category_params)
     if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to  @category
     else
        render 'new'
     end

    end

    def edit
     @category = Category.find(params[:id])
    end
    
    def update
      @category = Category.find(params[:id])
     if @category.update(category_params)
      flash[:notice] = "Ctegory name updated successfully"
      redirect_to @category
     else
      render 'edit'
     end
    end

    def index
      @categories = Category.paginate(page: params[:page], per_page: 2)
    end

    def show
     @category = Category.find(params[:id])
     @articles = @category.articles.paginate(page: params[:page], per_page: 2)
    end
   
    private 

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
     if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins an perform that action"
        redirect_to categories_path
     end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
     redirect_to articles_path if logged_in?
    end 

    def about
        
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
     user = User.find_by(email: params[:session][:email].downcase)
     if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
     else 
        flash.now[:alert] = "There was something wrong with your login details"
        render 'new'
     end
    end
    
    def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
     def show
      @articles = @user.articles.paginate(page: params[:page])
     end

     def index
      @users = User.paginate(page: params[:page], per_page: 2)
     end

    def new
        @user = User.new
    end
     
    def edit
    end
  
    def update
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        redirect_to @user
      else
        render 'edit'
      end
    end

    def create
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, You have successfully signed up"
        redirect_to articles_path
      else 
        render 'new'
      end 
    end
   
    def destroy
     @user.destroy
     session[:user_id] = nil if @user == current_user
     flash[:notice] = "Account and all associated articles successfully deleted"
     redirect_to articles_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end
    
    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own account"
        redirect_to @user
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def gravatar_for(user, options = { size: 80})
      email_address = user.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      size = options[:size]
      gravatar_url = "https://www.gravatar.com/avatar/#{hash}?d=wavatar"
      image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
<% @articles.each do |article|%>
<div class="row justify-content-md-center">
<div class="col-10 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
  <% if article.user %>
    by <%= link_to article.user.username, user_path(article.user)  %>
    <% end %>
     <% if article.categories.any? %>
   <div class="mt-2"><%= render article.categories %></div> 
        <% end  %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
    
     <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
      <% if logged_in? && (article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
        <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
         <% end %>
          </div>
  <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(article.created_at) %> ago,
 Edited <%= time_ago_in_words(article.updated_at) %> ago </smal>  
  </div>
</div>
</div>
</div>
<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @article %>
  <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-success rounded", local: true) do |f| %>

  <div class="form-group row">
    <%= f.label :title, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title" %>
  </div>
  </div>

  <div class="form-group row">
    <%= f.label :description, class: "col-2 col-form-label text-light" %> <br>
      <div class="col-10">
      <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description" %>
  </div>
  </div>

  <div class="form-group row">
    <%= f.label :category, class: "col-2 col-form-label text-light" %>
      <div class="col-10">
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
    { promt: "Make your selection from the list below (can be empty)"}, { multiple: true, class: "custom-select shadow rounded" }) %>
  </div>
  </div>


    <div class="form-group row justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>

  <% end %>
</div>
   <div class="mb-3">
  <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-info" %>
</div>
 </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>

    <%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles listing</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

 <%= render 'article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>

    <%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>

<div class="container">
<div class="row justify-content-md-center">
<div class="col-10 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
    by <%= @article.user.username if @article.user %>
    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
    <% if @article.categories.any? %>
   <div class="mt-2"><%= render @article.categories %></div> 
        <% end  %>
  </div>

  <div class="card-body">
    <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
          </div>
  <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
 Edited <%= time_ago_in_words(@article.updated_at) %>ago</smal>  
  </div>
</div>
<div class="container text-white bg-dark">
<h2 class=" text-center font-weight-5 text-success">Your opinion matters, Comment bellow</h2>
<% @article.comments.each do |comment| %>
  <p class="">
    <%= comment.body %>
  </p>
<% end %>

<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.text_area :body, class: "w-100" %>
  </p>
  <p class="text-center">
    <%= form.submit class: "btn btn-outline-primary" %>
  </p>
<% end %>
</div>

</div>
</div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge badge-pill badge-success mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
  <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-success rounded", local: true) do |f| %>

  <div class="form-group row">
    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category name" %>
  </div>
  </div>

    <div class="form-group row justify-content-center">
  <%= f.submit class: "btn btn-outline-light btn-lg" %>
  </div>

  <% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<div class="container">
  
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'form' %>
</div>
   <div class="mb-3">
  <%= link_to 'Cancel and return to category', category_path(@category), class: "text-success" %>
</div>
 </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>
<div class="container">
<% @categories.each do |category|%>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-body">
    <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
             <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
  <div class="card-footer text-muted">
 <small>Created <%= time_ago_in_words(category.created_at) %> ago,
 Edited <%= time_ago_in_words(category.updated_at) %> ago </smal>  
  </div>
</div>
</div>
</div>
<% end %>
</div>
<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
  </div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<div class="container">
  
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'form' %>
</div>
   <div class="mb-3">
  <%= link_to 'Cancel and return to categories listing', categories_path, class: "text-success" %>
</div>
 </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>
<% if logged_in? && current_user.admin? %>
<div class="text-center mt-4">
<%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
</div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

 <%= render 'articles/article' %>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
 <div class="container text-center">
 <small>Copyright &copy; <%= link_to "Shaher Shamroukh", "https://www.linkedin.com/in/shaher-shamroukh", target: "_blank", class: "namy" %></small>
 </div>
</footer>
    

app/views/layouts/_messages.html.erb
<div class="container">
  <%flash.each do |name, msg| %>
       <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    </div>
  <% end  %>
  </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-dark navbar-expand-lg">
      <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>   
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle success" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Articles
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "Create a new article", new_article_path, class: "dropdown-item" %>
            <% end %>
              <%= link_to "View article", articles_path, class: "dropdown-item" %>
          </li>
         
         
            <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create new category", new_category_path, class: "dropdown-item" %>
          <% end %>  
          <%= link_to "View categories", categories_path, class: "dropdown-item" %>
        </div>
      </li>


          <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle success" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             <%= "Adimn" if current_user.admin? %> <%= current_user.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"} %>
            </div>
          </li>
         
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
          </li>
          <% else %>
         <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
          </li>
         <% end  %>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
       <%= render 'layouts/navigation' %>
       <div id="page-content">
   <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<H1>This is the about page</H1>
<style>
h1 {
    color: red;
}
</style>
<%= link_to 'Articles listing', articles_path %> |
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
   <div class="jumbotron text-center text-white">
   <hr class="my-4">
   <div id="my-btn">
   <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
   </div>
   </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The folowing errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end  %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>  
  <% end  %>

app/views/users/_form.html.erb
<div class="container">
  
  <div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors', obj: @user %>
  <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-success rounded", local: true) do |f| %>

  <div class="form-group row">
    <%= f.label :username, class: "col-2 col-form-label text-light" %>
    <div class="col-10">
      <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
  </div>
  </div>

  <div class="form-group row">
    <%= f.label :email, class: "col-2 col-form-label text-light" %> <br>
      <div class="col-10">
      <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
  </div>
  </div>

  <div class="form-group row">
    <%= f.label :password, class: "col-2 col-form-label text-light" %> <br>
      <div class="col-10">
      <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
  </div>
  </div>

    <div class="form-group row justify-content-center">
  <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
  </div>

  <% end %>
</div>
   <div class="mb-3">
  <%= link_to 'Cancel and return to articles listing', articles_path, class: "text-success" %>
</div>
 </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit Your profile</h1>

    <%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<div class="container">
<% @users.each do |user|%>
<div class="row justify-content-md-center">
<div class="col-10 mt-4">
<div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
     <%= link_to user.username, user%>
  </div>
  <div class="card-body">
    <h5 class="card-title">
    <%= link_to gravatar_for(user, size: 150), user %></h5>
    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
    
       <%= link_to "View profile", user, class: "btn btn-outline-success" %>
       <% if logged_in? %>
          <%if user == current_user %>
       <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
          <% end %>
          <% if current_user.admin? %>
     <%= link_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete,
     data: {confirm: "Are you sure you want to delete user account and all associated articles?"} %>
              <% end %>
          <% end %>
          </div>
  <div class="card-footer text-muted">
 <small>Joined <%= time_ago_in_words(user.created_at) %> ago</smal>  
  </div>
</div>
</div>
</div>
<% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>

    <%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
<div class="text-center mt-4">
<%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
</div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
  </div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
  </div>